1. Write function which takes two parameters account no and name of the user.
Check if the account number is valid. Account no is valid only if it is a 4 digit number less than 5000
Check if the name is valid. Name is valid if all characters are alphabets and no numbers or special chars in the name
If both name and 'acc no' are valid return True
If acc no is invalid return a message string saying “Account no is invalid”
if name is invalid return None

In [ ]:

def name(acc_n,acc_num):
    if (acc_num<5000) and (acc_num>=1000):
        if acc_n.isalpha():
            return True
        else:
            return False
    else:
        return "Account no invalid"

name('Ramayan',3500)

True


2. WA function to calculate total salary given that
  1. post
  2. basic salary
rules:
post can be manager or employee
total sal = basic + TA + HRA
TA = 5000 for 'manager'
and TA = 10,000 for 'employee'
HRA = 20,000 for 'manager' and HRA = 12,000 for 'employee'

In [ ]:
def sal_cal(post,ba):
  if post.lower()=='manager':
    return "Salary of manager is ",(5000+20000+int(ba))
  elif post.lower()=='employee':
    return "Salary of Employee is ",(10000+12000+int(ba))
  else:
    return "Enter valid Inputs"

sal_cal("Employee",10000)

('Salary of Employee is ', 32000)

3.
WA function to rotate given string by 2 position to right

Ex.
s1=”IACSD”
Rotate by 2 place to right
“SDIAC”

In [ ]:
def rotate(name):
  name=name[-2:]+name[:-2]
  return name


rotate('IACSD')

'SDIAC'

4.  Generalize above function to rotate string to right by n

In [ ]:
def rotate(name,n):
  name=name[-n:]+name[:-n]
  return name


rotate('Happy_New_Year',3)

'earHappy_New_Y'

5.  Generalize above function to rotate string by n to right or left

In [ ]:
def rotate(name,n):
  name=name[n:]+name[:n]
  return name


rotate('Happy_New_Year',3)

'py_New_YearHap'

6. WAP to count number of passengers in every airline. Here we are given dictionary of passanger id and airline id
Ex
input_dir ={'p1':'a1','p2':'a10','p89':'a1','p5':'a10'}
output: {'a1':2, 'a10':2}

In [ ]:
def pas_count(**input_dir):
  # input_dir ={'p1':'a1','p2':'a10','p89':'a1','p5':'a10'}
  vals = list(input_dir.values())
  valsset = set(input_dir.values())
  # print(vals)
  # print(valsset)
  pas={}
  for i in valsset:
    pas[i]=vals.count(i)

  return (pas)

pas_count(p1='a1',p2='a10',p89='a1',p5='a10')

{'a1': 2, 'a10': 2}

7. given a list of strings.
every string is in format "Emp_name:Emp_id"
Emp_id is always a number
if emp_id is amstrong number then rotate emp_name 1 place to the right --> and print the emp_name
if emp_id is a prime no then print vowels from the employee name
in other cases print consonents from the emp name
Finally there should be print of every employee name as per given condition

In [144]:
import math
import sympy
def emp(e_details):
  ename, eno= e_details.split(":")
  sum=0

  # Checking Armstrong number
  for i in eno:
    sum+=math.pow(int(i),len(eno))

  if sum==int(eno):
    ename=ename[1:]+ename[0]
    # print(ename)                # output from condition 1

    #checking Prime number
  l1=[]
  if sympy.isprime(int(eno)):

    for i in ename:
       if i in ['a','e','i','o','u','A','E','I','O','U']:
        l1.append(i)         # output from condition 2
    # print("".join(l1))

  else:
    for i in ename:
       if i not in ['a','e','i','o','u','A','E','I','O','U']:
        l1.append(i)
    # print("".join(l1))


  return ename, ("".join(l1))




emp("Jonathan:28116440335967")  #prime+Armstrong
emp("Jonathan:153")             #Armstrong

('onathanJ', 'nthnJ')

8. Write a function which takes all details of a person as input in sequence and prints details as follows
(Hint: Think which type of parameter to be used for every option)
a. Take name and Print it in Camel Case
b. Take 10 digit Mobile No and print it appending +91
c. Take location as optional value. If not given then print India
d. Take Qualifications. Qualifications can be 1 or 2 or many.
Print all the passed qualifications one by one. Default qualification is "Human"

In [ ]:
def details(name, mo_no,/,loc,*edu):
  name1=name[0]
  name=name1.upper()+name[1:].lower()


  mo_no='+91'+str(mo_no)

  if loc ==None:
    loc='India'

  print("Name: ",name)
  print("Mobile_no: ",mo_no)
  print("Location: ",loc)
  print("Education: ",edu)


details('Tommy',9234567890,None,'10th','12th','Be')

Name:  Tommy
Mobile_no:  +919234567890
Location:  India
Education:  ('10th', '12th', 'Be')

9. Create a function "cloth_details" with three arguments, color, shape and size. All three are optional and can be passed in any sequence by the user.

In [ ]:
def cloth_details(color='black',shape='Rectangle',size='XL'):
    print("color :",color)
    print("shape :",shape)
    print("size :",size)

cloth_details(color='Black',size='XXL',shape='Square')

color : Black
shape : Square
size : XXL

10. Create a calculator.py file
Create add(), subtract(), multiply(), divide(), power(), log() functions
Create a menu driven program to take values and operation as input from user and print result using these functions


Take ONLY integer inputs from user. If its not an integer then give Error message -> "WRONG Input: Please enter ONLY integer value"
Your program should not give "ValueError" while using int() function for any input from below, It should display YOUR error message
Enter a number : 10
Enter a number : 10.9
Enter a number : ABC
(Hint: Think about methods from string data type to check input as integer)

In [ ]:
def caltr(num1,num2):
    if(num1.isdigit() and num2.isdigit()):
        num1=int(num1)
        num2=int(num2)
    else:
        return ("Enter Valid Number")

    print("Enter the choice \n 1.Addition \n 2.Substraction \n 3.Multiplication \n 4.Division \n 5.Power \n 6.Log")
    choice=input("Enter Choice")
    var1=choice1(num1,num2,choice)
    return var1

def choice1(a,b,c):
    import math
    match c:
        case "1":
            return a+b
        case "2":
            return a-b
        case "3":
            return a*b
        case "4":
            return a/b
        case "5":
            return a**b
        case "6":
            return math.log(a,b)

        case _:
            return "Wrong choice entered"

number1=input("Enter the num1:")
number2=input("Enter the num2:")

var=caltr(number1, number2)
print(var)

Enter the num1:5
Enter the num2:4
Enter the choice
 1.Addition
 2.Substraction
 3.Multiplication
 4.Division
 5.Power
 6.Log
Enter Choice1
9

11. Write a function which finds average of given arguments. Minimum it takes two parameters and maximum it can take any number of arguments.
Finally it should return average of all arguments passed

Ex. avg(10,12)  return value 11
avg(3,4,5)  return value 4
avg(1,2,3,4,5,6,7,8,9,10) return value 5.5
Extra case
avg(1,2,avg(4,5,6)) return value 2.667 (roughly 8/3)

In [ ]:
def avg(l):
  l= l.split()
  l1=[]
  total=0
  for i in l:
    i=int(i)
    l1.append(i)
    total+=i

  return (total/len(l1))


avg('25 34 64 23')

36.5